development:
  adapter: postgresql
  encoding: unicode
  database: testone_development
  pool: 5
  username: natalie
  password: 2246

test:
  adapter: postgresql
  encoding: unicode
  database: testone_test
  pool: 5
  username: natalie
  password: 2246
